### PR TITLE
auto-ack off

### PR DESCRIPTION
**Pull request by alexbyrnes**
## What does this PR do?
Turns off auto ack. The library we're using has a memory problem caused by auto ack. 

https://github.com/streadway/amqp/issues/149

## How do I test this PR?

publish events to rabbitmq from pillar and consume them in another service using pillar's amqp.go.  You should see publishes, delivers, and acks. You shouldn't see any no "Deliver (noack)" in the rabbitmq admin console (http://localhost:15672/ if you're running it locally). 

@coralproject/backend

### CODE REVIEW

**Comment by gabelula** [comment]
Are you calling the delivery.ack somewhere else?

**Comment by alexbyrnes** [comment]
It gets called in the subscriber aka wake.

```go

	msgs, err := mq.Receive()
	failOnError(err, "Failed to register a consumer")

	forever := make(chan bool)
	go func() {
		for d := range msgs {
                       
                        // some stuff

			d.Ack(false)
		}
	}()
```

**Comment by gabelula** [comment]
And that is code is not here? 

The code that wake is using is this one: https://github.com/coralproject/pillar/blob/master/app/wake/listener/listener.go

right?

**Comment by alexbyrnes** [comment]
yes that's a good point. I didn't realize there was a copy in pillar too

**Comment by kgardnr** [comment]
We should either delete this if it didn't fix the issue, or go ahead and merge it. I'll move to Backlog for now.

**Comment by alexbyrnes** [comment]
#143 was the fix. I think we should delete this to keep things simple.  We can restore it if we need acks at some point.

**Comment by jde** [comment]
Closing as unneeded.

**Pull request closed without merging**
