### PR TITLE
Supporting CORS pre-flight on tags.

### PR DESCRIPTION
**Pull request by pablocubico**
No need to merge this PR, I just wanted to show you the hack I had to do to get it working with Cay.

We are using fetch() on the front-end, which uses CORS and sends a pre-flight OPTIONS request to ask for available methods on the API side. 

Looks like the default setup of the Gorilla handlers CORS middleware do not handle CORS requests as I expected, maybe tweaking the initialization options would do the trick.

I had to manually set the OPTIONS pre-flight response and CORS headers on each of the tags API entries, but I assume there should be a more generic way of doing this, maybe wrapping the router on creation.

Adding an issue on this.

### CODE REVIEW

**Comment by jde** [comment]
This is going to be something that comes up more and more.  We need a good CORS implementation.  This is a good way to do it with the assumption that any OPTIONS request will result in full access (which is sufficient for this purpose.) 

This is handled via xenia's web library like so: https://github.com/coralproject/xenia/blob/master/cmd/xeniad/routes/routes.go#L64

I'll merge this for now in leu of our pending architectural conversation concerning committing to a framework.

**Comment by pablocubico** [comment]
There's a generalization proposed by Sam here:

https://github.com/coralproject/pillar/issues/39

**Comment by riley** [comment]
what's the status of this? we're going to need it for the User Manager screen for the partner launch.

**Comment by pablocubico** [comment]
Let me merge master back to my branch and I'll push what Sam suggested.

**Comment by pablocubico** [comment]
Ok, it's ready to merge, the proposed generic solution did not work for me, this one still does (but it's just for the tags endpoints)..

In the future, I think we should use the same approach Xenia uses, to make all our Go codebases consistent.

**Comment by samshub** [comment]
Please go ahead with your change. Thanks

**Pull request merged**
