### PR TITLE
Fix for https://github.com/coralproject/pillar/issues/16

### PR DESCRIPTION
**Pull request by samshub**
Here are minimal requirement to run Pillar in a Docker container:

> The app must be able to read mongo credentials and any other info
> The app must write log files to a certain location

Proposed Solution:
Define an env variable ```PILLAR_HOME``` to a location where the server will be deployed.

~~~
export PILLAR_HOME=/opt/pillar
~~~

The server expects to read various information from ```$PILLAR_HOME/pillar.json``` file. Here is how this might look:

~~~
{    
    "mongo_url": "mongodb://localhost:27017/coral"
}
~~~

Runtime, the server will write logs to ```$PILLAR_HOME/logs/pillar.log```

### CODE REVIEW

**Comment by frnsys** [comment]
Looks good! For atoll, the config is a yaml file - do you think it should be json for consistency? (or the other way around?)

**Comment by gabelula** [comment]
Yes. I think we have the configuration yaml or json but have it all the same.

**Comment by samshub** [comment]
```golang``` has built-in support for ```json```, so no extra work was needed. I wouldn't worry about yaml vs json, esp since it is a different application using a different language.

**Comment by samshub** [comment]
Looks like pillar.json can be extracted out from the container. So the best option is to pass information using the ```--env-file``` option in ```docker run``` command.

https://docs.docker.com/engine/reference/commandline/run/

More changes coming....

**Comment by samshub** [comment]
Instructions on how to run pillar/server using docker

a. define an env.ist file with two vars

~~~
PILLAR_HOME=/opt/pillar
MONGODB_URL=mongodb://192.xxx.xxx.xxx:27017/coral
~~~

b. Run the container and pass the env.list

~~~
docker run --env-file ./env.list --publish 8080:8080 b702cdc9cf3e
~~~

**Pull request merged**
